
spring:
    datasource:
        url: jdbc:h2:mem:deneb
        driver-class-name: org.h2.Driver
        username: sa
        password: ''
    h2:
        console:
            enabled: true
    jpa:
        show-sql: true
    profiles:
        active: local

---

spring:
    datasource:
        url: jdbc:p6spy:h2:mem:deneb
        driver-class-name: com.p6spy.engine.spy.P6SpyDriver
        username: sa
        password: ''
    config:
        activate:
            on-profile: dev
